{% set name = "easygui" %}
{% set version = "0.98.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d653ff79ee1f42f63b5a090f2f98ce02335d86ad8963b3ce2661805cafe99a04

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  requires:
    - xorg-libx11  # [linux]
  imports:
    - easygui
    - easygui.boxes

about:
  home: https://github.com/robertlugg/easygui
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: EasyGUI is a module for very simple, very easy GUI programming in Python.  EasyGUI is different from other GUI generators in that EasyGUI is NOT event-driven.  Instead, all GUI interactions are invoked by simple function calls.

extra:
  recipe-maintainers:
    - marcelotrevisani
